declare namespace molmil {
    const SNFG: any;
}
declare namespace molmil {
    function localStorageGET(field: any, except: any): any;
}
declare namespace molmil {
    var canvasList: any[];
    var mouseDown: boolean;
    var mouseDownS: {};
    var mouseMoved: boolean;
    var Xcoord: number;
    var Ycoord: number;
    var Zcoord: number;
    var activeCanvas: any;
    var touchList: any;
    var touchMode: boolean;
    var preRenderFuncs: any[];
    var longTouchTID: any;
    var previousTouchEvent: any;
    var ignoreBlackList: boolean;
    var vrDisplay: any;
    var vrPose: number[];
    var vrOrient: number[];
    var pdbj_data: string;
    const settings_default: {
        src: string;
        pdb_url: string;
        pdb_chain_url: string;
        comp_url: string;
        data_url: string;
        newweb_rest: string;
        molmil_video_url: any;
        dependencies: string[];
    };
    var cli_canvas: any;
    var cli_soup: any;
    var settings: any;
    const configBox: {
        version: number;
        buildDate: any;
        initFinished: boolean;
        liteMode: boolean;
        cullFace: boolean;
        loadModelsSeparately: boolean;
        wheelZoomRequiresCtrl: boolean;
        recordingMode: boolean;
        save_pdb_chain_only_change: boolean;
        xna_force_C1p: any;
        vdwR: {
            DUMMY: number;
            H: number;
            He: number;
            Li: number;
            Be: number;
            B: number;
            C: number;
            N: number;
            O: number;
            F: number;
            Ne: number;
            Na: number;
            Mg: number;
            Al: number;
            Si: number;
            P: number;
            S: number;
            Cl: number;
            Ar: number;
            K: number;
            Ca: number;
            Sc: number;
            Ti: number;
            V: number;
            Cr: number;
            Mn: number;
            Fe: number;
            Ni: number;
            Cu: number;
            Zn: number;
            Ga: number;
            Ge: number;
            As: number;
            Se: number;
            Br: number;
            Kr: number;
            Rb: number;
            Sr: number;
            Pd: number;
            Ag: number;
            Cd: number;
            In: number;
            Sn: number;
            Sb: number;
            Te: number;
            I: number;
            Xe: number;
            Cs: number;
            Ba: number;
            Pt: number;
            Au: number;
            Hg: number;
            Tl: number;
            Pb: number;
            Bi: number;
            Po: number;
            At: number;
            Rn: number;
            Fr: number;
            Ra: number;
            U: number;
        };
        MW: {
            H: number;
            He: number;
            Li: number;
            Be: number;
            B: number;
            C: number;
            N: number;
            O: number;
            F: number;
            Ne: number;
            Na: number;
            Mg: number;
            Al: number;
            Si: number;
            P: number;
            S: number;
            Cl: number;
            K: number;
            Ar: number;
            Ca: number;
            Sc: number;
            Ti: number;
            V: number;
            Cr: number;
            Mn: number;
            Fe: number;
            Ni: number;
            Co: number;
            Cu: number;
            Zn: number;
            Ga: number;
            Ge: number;
            As: number;
            Se: number;
            Br: number;
            Kr: number;
            Rb: number;
            Sr: number;
            Y: number;
            Zr: number;
            Nb: number;
            Mo: number;
            Tc: number;
            Ru: number;
            Rh: number;
            Pd: number;
            Ag: number;
            Cd: number;
            In: number;
            Sn: number;
            Sb: number;
            I: number;
            Te: number;
            Xe: number;
            Cs: number;
            Ba: number;
            La: number;
            Ce: number;
            Pr: number;
            Nd: number;
            Pm: number;
            Sm: number;
            Eu: number;
            Gd: number;
            Tb: number;
            Dy: number;
            Ho: number;
            Er: number;
            Tm: number;
            Yb: number;
            Lu: number;
            Hf: number;
            Ta: number;
            W: number;
            Re: number;
            Os: number;
            Ir: number;
            Pt: number;
            Au: number;
            Hg: number;
            Tl: number;
            Pb: number;
            Bi: number;
            Po: number;
            At: number;
            Rn: number;
            Fr: number;
            Ra: number;
            Ac: number;
            Pa: number;
            Th: number;
            Np: number;
            U: number;
            Am: number;
            Pu: number;
            Cm: number;
            Bk: number;
            Cf: number;
            Es: number;
            Fm: number;
            Md: number;
            No: number;
            Rf: number;
            Lr: number;
            Db: number;
            Bh: number;
            Sg: number;
            Mt: number;
            Rg: number;
            Hs: number;
        };
        sndStrucInfo: {
            1: number[];
            2: number[];
            3: number[];
            4: number[];
        };
        zNear: number;
        zFar: number;
        QLV_SETTINGS: {
            SPHERE_TESS_LV: number;
            CB_NOI: number;
            CB_NOVPR: number;
            CB_DOME_TESS_LV: number;
        }[];
        OES_element_index_uint: any;
        EXT_frag_depth: any;
        imposterSpheres: boolean;
        BGCOLOR: number[];
        backboneAtoms4Display: {
            N: number;
            C: number;
            O: number;
            H: number;
            OXT: number;
            OC1: number;
            OC2: number;
            H1: number;
            H2: number;
            H3: number;
            HA: number;
            HA2: number;
            HA3: number;
            CN: number;
            CM: number;
            CH3: number;
        };
        projectionMode: number;
        colorMode: number;
        smoothFactor: number;
        glsl_shaders: string[][];
        glsl_fog: number;
        skipClearGeometryBuffer: boolean;
        stereoMode: number;
        stereoFocalFraction: number;
        stereoEyeSepFraction: number;
        camera_fovy: number;
        HQsurface_gridSpacing: number;
        webGL2: boolean;
        vdwSphereMultiplier: number;
        stickRadius: number;
        groupColorFirstH: number;
        groupColorLastH: number;
        cartoon_highlight_color: number[];
        connect_cutoff: number;
        orientMODELs: boolean;
        chainHideCutoff: number;
        video_framerate: number;
        video_path: string;
        skipChainSplitting: boolean;
    };
    const AATypes: {
        ALA: number;
        CYS: number;
        ASP: number;
        GLU: number;
        PHE: number;
        GLY: number;
        HIS: number;
        ILE: number;
        LYS: number;
        LEU: number;
        MET: number;
        ASN: number;
        PRO: number;
        GLN: number;
        ARG: number;
        SER: number;
        THR: number;
        VAL: number;
        TRP: number;
        TYR: number;
        ACE: number;
        NME: number;
        NH2: number;
        HIP: number;
        HIE: number;
        HID: number;
        CYX: number;
        PTR: number;
        A: number;
        T: number;
        G: number;
        C: number;
        DA: number;
        DT: number;
        DG: number;
        DC: number;
        U: number;
        DU: number;
        U5: number;
        U3: number;
        A5: number;
        MSE: number;
        SEQ: number;
        CSW: number;
        ALY: number;
        CYM: number;
    };
    const AATypesBase: {
        ALA: number;
        CYS: number;
        ASP: number;
        GLU: number;
        PHE: number;
        GLY: number;
        HIS: number;
        ILE: number;
        LYS: number;
        LEU: number;
        MET: number;
        ASN: number;
        PRO: number;
        GLN: number;
        ARG: number;
        SER: number;
        THR: number;
        VAL: number;
        TRP: number;
        TYR: number;
        ACE: number;
        NME: number;
        NH2: number;
        HIP: number;
        HIE: number;
        HID: number;
        CYM: number;
    };
}
declare function findResidueRings(molObj: any): any;
declare function renderHbonds(pairs: any, soup: any, settings: any): any;
declare function renderPIinteractions(pairs: any, soup: any): any;
declare function renderSaltBridges(pairs: any, soup: any): any[];
declare function processExternalCommand(cmd: any, commandBuffer: any): void;
